# Generated by Django 3.1.7 on 2021-04-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210416_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
