# Generated by Django 3.1.7 on 2021-04-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_profile',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
