# Generated by Django 3.1.7 on 2021-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210417_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_profile',
            name='aadhar_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='new_profile',
            name='contact_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
