# Generated by Django 3.1.7 on 2021-04-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210422_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='new_profile',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='new_profile',
            name='profile_picture',
            field=models.ImageField(default='default/download.jpg', upload_to='pics'),
        ),
    ]
