# Generated by Django 3.1.7 on 2021-04-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210423_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_profile',
            name='profile_picture',
            field=models.ImageField(default='default/ppf.png', upload_to='pics'),
        ),
    ]
