# Generated by Django 3.1.7 on 2021-04-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20210423_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_profile',
            name='profile_picture',
            field=models.ImageField(default='media/default/ppf.jpeg', upload_to='pics'),
        ),
    ]
