# Generated by Django 3.1.7 on 2021-04-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20210425_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_profile',
            name='profile_picture',
            field=models.ImageField(default='default/download.jpg', upload_to='pics'),
        ),
    ]
