# Generated by Django 3.1.7 on 2021-04-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20210427_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_profile',
            name='profile_picture',
            field=models.ImageField(default='media/default/download.jpg', upload_to='pics'),
        ),
    ]
