# Generated by Django 3.1.7 on 2021-05-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_auto_20210427_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_profile',
            name='regname',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
