# Generated by Django 3.1.7 on 2021-06-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_new_profile_regname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_profile',
            name='profile_picture',
            field=models.ImageField(default='default/download.jpg', upload_to='pics'),
        ),
    ]
