# Generated by Django 3.1.7 on 2021-06-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_auto_20210613_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_profile',
            name='address',
            field=models.TextField(default='LkO'),
        ),
    ]
