# Generated by Django 3.1.7 on 2021-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default=1111, max_length=12),
            preserve_default=False,
        ),
    ]
