# Generated by Django 3.1.7 on 2021-06-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210615_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='address',
            field=models.TextField(default='LKO'),
        ),
    ]
