# Generated by Django 3.1.7 on 2021-06-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_services_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='cate',
            new_name='cat_name',
        ),
    ]
