# Generated by Django 3.1.7 on 2021-06-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210627_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='cat_name',
            new_name='category',
        ),
    ]
