# Generated by Django 3.1.7 on 2021-06-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210627_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='category',
            new_name='cate',
        ),
    ]
