# Generated by Django 3.1.7 on 2021-06-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210627_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='imag',
            field=models.ImageField(default=1111111111111111, upload_to='pic'),
            preserve_default=False,
        ),
    ]
