# Generated by Django 3.1.7 on 2021-07-02 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cart_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Services',
            new_name='imaging',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='imag',
        ),
        migrations.AddField(
            model_name='cart',
            name='catego',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='Available_qunatitiy',
            field=models.IntegerField(default=5),
        ),
    ]
