# Generated by Django 3.1.7 on 2021-07-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210702_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='catego',
        ),
    ]
